### ISSUE TITLE
Draft an key-value store schema to associate containers with their related openflow rules and policies

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/dynamic-netsec#30]
For now, you can draw a DB schema or some tables. We can then translate them into k-v objects later when we agree on a final schema.

Motive: We would like to associate all containers with their network policies and openflow rules that apply to them. We further need to maintain information about where (one which host) each container lives, along with the associated container network identifiers and interfaces (e.g. IP, MAC Addresses, ... etc)

**Comment by xiecancn** [comment]
The policy schema heavily depends on the architecture paradigm we choose to use. Two often used paradigms for adaptive policy are **MAPE-K**(Monitor, Analysis, Plan, Execute over a Knowledge base) and **ECA** (Event Condition Action).

If we are going to use te ECA, some filed I think the schema should contain are 
```
    policyName:
    policyID:
   
    subject: <domain-scope-expression>
    onEvent: <event-list>
    condition: <constraint_expression>
    target: <domain-scope-expression>
    action: <action-list> (block | migrate | rate_limit | route ...)
    rules: <rule-id-list>
```
e.g. If at least one of the red links ic congested, apply rate_limiting to the authentication service.
Policy: 
```
    ...
    onEvent: one-link-congested event
    target: select service[metadata][container_name] where service[name] = "authentication"
    action: rate_limit(target, options)
    ...
```
A use case will be helpful for me to draft the concrete schema.
